project:
  type: website
  output-dir: docs

website:
  title: "Alexandrea Cole Patino"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
      - Research Projects.qmd
      - Posts.qmd
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

