project:
  type: website
  output-dir: docs

website:
  title: "Alexandrea Cole Patino"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
      - Research Projects.qmd
      - icon: github
        href: https://github.com/acpopal
    background: secondary
    search: true
    pinned: true
  page-footer:
    left: © Copyright 2024, Alexandrea Cole Patino
        
format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true

editor: visual

